<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="EasyNetQ" Version="8.1.0" />
		<PackageReference Include="Polly" Version="8.6.5" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\DM.Core\DM.Core.csproj" />
  </ItemGroup>

</Project>
