<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>d55cfa89-3e58-4163-9be5-1b2cd479e07e</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
		<PackageReference Include="NSwag.AspNetCore" Version="14.6.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.2" />
		<PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.1" />
		<PackageReference Include="NetDevPack.Security.JwtExtensions" Version="9.0.1" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
	</ItemGroup>

	<ItemGroup Label="Databases">
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.2" />

	</ItemGroup>

	<ItemGroup Label="HealthCheck">
		<PackageReference Include="AspNetCore.HealthChecks.MySql" Version="9.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" Version="9.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.Sqlite" Version="9.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DM.Core\DM.Core.csproj" />
		<ProjectReference Include="..\DM.MessageBus\DM.MessageBus.csproj" />
	</ItemGroup>

</Project>
