<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f7e09fbd-05ae-42b8-9d10-9b5bbc6b2901</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <!--<PackageReference Include="NetDevPack.Identity" Version="8.0.0" />
    <PackageReference Include="NetDevPack.Security.Jwt.AspNetCore" Version="9.0.4" />
    <PackageReference Include="NetDevPack.Security.Jwt.Store.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="NetDevPack.Security.PasswordHasher.Argon2" Version="7.1.2" />-->
	<PackageReference Include="NetDevPack.Security.JwtSigningCredentials.AspNetCore" Version="1.0.3" />
	<PackageReference Include="NetDevPack.Security.JwtSigningCredentials.Store.EntityFrameworkCore" Version="1.0.3" />

	<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\building blocks\DM.Core\DM.Core.csproj" />
    <ProjectReference Include="..\..\building blocks\DM.MessageBus\DM.MessageBus.csproj" />
    <ProjectReference Include="..\..\building blocks\DM.WebAPI.Core\DM.WebAPI.Core.csproj" />
  </ItemGroup>

</Project>
